"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import iotics.api.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Feed(google.protobuf.message.Message):
    """A feed representation."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    TWINID_FIELD_NUMBER: builtins.int
    @property
    def id(self) -> iotics.api.common_pb2.FeedID:
        """Feed identifier (unique within the scope of a twin identifier's feed set)"""
        pass
    @property
    def twinId(self) -> iotics.api.common_pb2.TwinID:
        """Twin unique identifier (twin to which the feed belongs)"""
        pass
    def __init__(self,
        *,
        id: typing.Optional[iotics.api.common_pb2.FeedID] = ...,
        twinId: typing.Optional[iotics.api.common_pb2.TwinID] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","twinId",b"twinId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","twinId",b"twinId"]) -> None: ...
global___Feed = Feed

class CreateFeedRequest(google.protobuf.message.Message):
    """CreateFeedRequestCreate is used to create a new feed in a given twin."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """Payload describes the data needed to create a feed."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEEDID_FIELD_NUMBER: builtins.int
        @property
        def feedId(self) -> iotics.api.common_pb2.FeedID:
            """ID of the feed to create
            StoreLast indicates if the last received value should be stored of not
            """
            pass
        def __init__(self,
            *,
            feedId: typing.Optional[iotics.api.common_pb2.FeedID] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feedId",b"feedId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feedId",b"feedId"]) -> None: ...

    class Arguments(google.protobuf.message.Message):
        """Arguments describes the mandatory arguments to identify the twin the feed belongs to."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        TWINID_FIELD_NUMBER: builtins.int
        @property
        def twinId(self) -> iotics.api.common_pb2.TwinID:
            """Identifier of the twin owning this feed"""
            pass
        def __init__(self,
            *,
            twinId: typing.Optional[iotics.api.common_pb2.TwinID] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["twinId",b"twinId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["twinId",b"twinId"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """CreateFeedRequest headers"""
        pass
    @property
    def args(self) -> global___CreateFeedRequest.Arguments:
        """CreateFeedRequest mandatory arguments"""
        pass
    @property
    def payload(self) -> global___CreateFeedRequest.Payload:
        """CreateFeedRequest payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___CreateFeedRequest.Arguments] = ...,
        payload: typing.Optional[global___CreateFeedRequest.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> None: ...
global___CreateFeedRequest = CreateFeedRequest

class CreateFeedResponse(google.protobuf.message.Message):
    """CreateFeedResponse describes a created feed."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """CreateFeedResponse payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """The created feed"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """CreateFeedResponse headers"""
        pass
    @property
    def payload(self) -> global___CreateFeedResponse.Payload:
        """CreateFeedResponse payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___CreateFeedResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___CreateFeedResponse = CreateFeedResponse

class DeleteFeedRequest(google.protobuf.message.Message):
    """DeleteFeedRequest is used to delete a feed from a given twin."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Arguments(google.protobuf.message.Message):
        """DeleteFeedRequest arguments."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Feed to delete"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DeleteFeedRequest headers"""
        pass
    @property
    def args(self) -> global___DeleteFeedRequest.Arguments:
        """DeleteFeedRequest mandatory arguments"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___DeleteFeedRequest.Arguments] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers"]) -> None: ...
global___DeleteFeedRequest = DeleteFeedRequest

class DeleteFeedResponse(google.protobuf.message.Message):
    """DeleteFeedResponse describes a deleted feed."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """DeleteFeedResponse payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Deleted feed"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DeleteFeedResponse headers"""
        pass
    @property
    def payload(self) -> global___DeleteFeedResponse.Payload:
        """DeleteFeedResponse payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___DeleteFeedResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___DeleteFeedResponse = DeleteFeedResponse

class UpdateFeedRequest(google.protobuf.message.Message):
    """UpdateFeedRequest is used to update attributes (including metadata) of a given feed."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """UpdateFeedRequest payload. One or more fields can be provided, depending on what needs to be updated.
        Note that the specified metadata changes are applied in the following order:
        tags, values, labels, comments
        """
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        STORELAST_FIELD_NUMBER: builtins.int
        VALUES_FIELD_NUMBER: builtins.int
        PROPERTIES_FIELD_NUMBER: builtins.int
        @property
        def storeLast(self) -> google.protobuf.wrappers_pb2.BoolValue:
            """StoreLast dictates whether to store the last shared sample of a feed."""
            pass
        @property
        def values(self) -> iotics.api.common_pb2.Values:
            """Values are descriptive individual data items to add/remove."""
            pass
        @property
        def properties(self) -> iotics.api.common_pb2.PropertyUpdate:
            """Custom properties to add/remove. Internal properties (such as location) cannot be modified here."""
            pass
        def __init__(self,
            *,
            storeLast: typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
            values: typing.Optional[iotics.api.common_pb2.Values] = ...,
            properties: typing.Optional[iotics.api.common_pb2.PropertyUpdate] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["properties",b"properties","storeLast",b"storeLast","values",b"values"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["properties",b"properties","storeLast",b"storeLast","values",b"values"]) -> None: ...

    class Arguments(google.protobuf.message.Message):
        """UpdateFeedRequest arguments."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed: ...
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """UpdateFeedRequest headers"""
        pass
    @property
    def args(self) -> global___UpdateFeedRequest.Arguments:
        """UpdateFeedRequest arguments"""
        pass
    @property
    def payload(self) -> global___UpdateFeedRequest.Payload:
        """UpdateFeedRequest payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___UpdateFeedRequest.Arguments] = ...,
        payload: typing.Optional[global___UpdateFeedRequest.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> None: ...
global___UpdateFeedRequest = UpdateFeedRequest

class UpdateFeedResponse(google.protobuf.message.Message):
    """UpdateFeedResponse is used to indicate a successful update."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """UpdateFeedResponse payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Updated feed"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """UpdateFeedResponse headers"""
        pass
    @property
    def payload(self) -> global___UpdateFeedResponse.Payload:
        """UpdateFeedResponse payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___UpdateFeedResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___UpdateFeedResponse = UpdateFeedResponse

class ShareFeedDataRequest(google.protobuf.message.Message):
    """ShareFeedDataRequest is used to share a new sample of data for the given feed."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """ShareFeedDataRequest payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SAMPLE_FIELD_NUMBER: builtins.int
        @property
        def sample(self) -> iotics.api.common_pb2.FeedData:
            """Sample to share"""
            pass
        def __init__(self,
            *,
            sample: typing.Optional[iotics.api.common_pb2.FeedData] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["sample",b"sample"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["sample",b"sample"]) -> None: ...

    class Arguments(google.protobuf.message.Message):
        """ShareFeedDataRequest arguments."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Feed sharing the sample"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ShareFeedDataRequest headers"""
        pass
    @property
    def args(self) -> global___ShareFeedDataRequest.Arguments:
        """ShareFeedDataRequest arguments"""
        pass
    @property
    def payload(self) -> global___ShareFeedDataRequest.Payload:
        """ShareFeedDataRequest payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___ShareFeedDataRequest.Arguments] = ...,
        payload: typing.Optional[global___ShareFeedDataRequest.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","payload",b"payload"]) -> None: ...
global___ShareFeedDataRequest = ShareFeedDataRequest

class ShareFeedDataResponse(google.protobuf.message.Message):
    """ShareFeedDataResponse is used to indicate a successful feed share."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADERS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ShareFeedDataResponse headers"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers"]) -> None: ...
global___ShareFeedDataResponse = ShareFeedDataResponse

class ListAllFeedsRequest(google.protobuf.message.Message):
    """ListAllFeedsRequest is used to list all the feeds owned by a given twin."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Arguments(google.protobuf.message.Message):
        """ListAllFeedsRequest mandatory arguments."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        TWINID_FIELD_NUMBER: builtins.int
        @property
        def twinId(self) -> iotics.api.common_pb2.TwinID:
            """Identifier of the twin owning this feed"""
            pass
        def __init__(self,
            *,
            twinId: typing.Optional[iotics.api.common_pb2.TwinID] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["twinId",b"twinId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["twinId",b"twinId"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    RANGE_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ListAllFeedsRequest headers"""
        pass
    @property
    def args(self) -> global___ListAllFeedsRequest.Arguments:
        """ListAllFeedsRequest arguments"""
        pass
    @property
    def range(self) -> iotics.api.common_pb2.Range:
        """Limit the results according to the value
        (optional: when not supplied, assume no default limits required - See https://ioticlabs.atlassian.net/browse/FO-1362)
        """
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___ListAllFeedsRequest.Arguments] = ...,
        range: typing.Optional[iotics.api.common_pb2.Range] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","range",b"range"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers","range",b"range"]) -> None: ...
global___ListAllFeedsRequest = ListAllFeedsRequest

class ListAllFeedsResponse(google.protobuf.message.Message):
    """ListAllFeedsResponse describes the list of the feeds owned by a twin."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """ListAllFeedsResponse payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEEDS_FIELD_NUMBER: builtins.int
        @property
        def feeds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Feed]:
            """List of the feeds owned by the twin"""
            pass
        def __init__(self,
            *,
            feeds: typing.Optional[typing.Iterable[global___Feed]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["feeds",b"feeds"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ListAllFeedsResponse headers"""
        pass
    @property
    def payload(self) -> global___ListAllFeedsResponse.Payload:
        """ListAllFeedsResponse payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___ListAllFeedsResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___ListAllFeedsResponse = ListAllFeedsResponse

class DescribeFeedRequest(google.protobuf.message.Message):
    """Description of twin: Provides public metadata lookup for individual resources."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Arguments(google.protobuf.message.Message):
        """DescribeFeedRequest arguments."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        REMOTEHOSTID_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Feed to describe"""
            pass
        @property
        def remoteHostId(self) -> iotics.api.common_pb2.HostID:
            """HostID to describe a remote feed (Optional, keep empty if feed is local)"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            remoteHostId: typing.Optional[iotics.api.common_pb2.HostID] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed","remoteHostId",b"remoteHostId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed","remoteHostId",b"remoteHostId"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DescribeFeedRequest headers"""
        pass
    @property
    def args(self) -> global___DescribeFeedRequest.Arguments:
        """DescribeFeedRequest mandatory arguments"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        args: typing.Optional[global___DescribeFeedRequest.Arguments] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args",b"args","headers",b"headers"]) -> None: ...
global___DescribeFeedRequest = DescribeFeedRequest

class DescribeFeedResponse(google.protobuf.message.Message):
    """Describe feed response."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class MetaResult(google.protobuf.message.Message):
        """Metadata result databag."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        VALUES_FIELD_NUMBER: builtins.int
        STORELAST_FIELD_NUMBER: builtins.int
        PROPERTIES_FIELD_NUMBER: builtins.int
        @property
        def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[iotics.api.common_pb2.Value]:
            """Values semantically describing the share payload of Feed"""
            pass
        storeLast: builtins.bool
        """Whether this feed might have its most recent data sample stored. If so, it can be retrieved via FetchLastStored
        request. (See interest API)
        """

        @property
        def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[iotics.api.common_pb2.Property]:
            """Custom properties associated with this feed."""
            pass
        def __init__(self,
            *,
            values: typing.Optional[typing.Iterable[iotics.api.common_pb2.Value]] = ...,
            storeLast: builtins.bool = ...,
            properties: typing.Optional[typing.Iterable[iotics.api.common_pb2.Property]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["properties",b"properties","storeLast",b"storeLast","values",b"values"]) -> None: ...

    class Payload(google.protobuf.message.Message):
        """DescribeFeedResponse payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FEED_FIELD_NUMBER: builtins.int
        RESULT_FIELD_NUMBER: builtins.int
        REMOTEHOSTID_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> global___Feed:
            """Described feed"""
            pass
        @property
        def result(self) -> global___DescribeFeedResponse.MetaResult:
            """Metadata result"""
            pass
        @property
        def remoteHostId(self) -> iotics.api.common_pb2.HostID:
            """HostID of the described feed. (Optional, empty if feed is local)"""
            pass
        def __init__(self,
            *,
            feed: typing.Optional[global___Feed] = ...,
            result: typing.Optional[global___DescribeFeedResponse.MetaResult] = ...,
            remoteHostId: typing.Optional[iotics.api.common_pb2.HostID] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed",b"feed","remoteHostId",b"remoteHostId","result",b"result"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed",b"feed","remoteHostId",b"remoteHostId","result",b"result"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DescribeFeedResponse headers"""
        pass
    @property
    def payload(self) -> global___DescribeFeedResponse.Payload:
        """DescribeFeedResponse payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___DescribeFeedResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___DescribeFeedResponse = DescribeFeedResponse

class UpsertFeedWithMeta(google.protobuf.message.Message):
    """UpsertFeedWithMeta is used to describe the full feed state. Used in UpsertTwinRequest."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    STORELAST_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    PROPERTIES_FIELD_NUMBER: builtins.int
    id: typing.Text
    """Id of the feed to create/update"""

    storeLast: builtins.bool
    """StoreLast dictates whether to store the last shared sample of the feed. Default 'False'"""

    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[iotics.api.common_pb2.Value]:
        """Values to set"""
        pass
    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[iotics.api.common_pb2.Property]:
        """Feed properties to set"""
        pass
    def __init__(self,
        *,
        id: typing.Text = ...,
        storeLast: builtins.bool = ...,
        values: typing.Optional[typing.Iterable[iotics.api.common_pb2.Value]] = ...,
        properties: typing.Optional[typing.Iterable[iotics.api.common_pb2.Property]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","properties",b"properties","storeLast",b"storeLast","values",b"values"]) -> None: ...
global___UpsertFeedWithMeta = UpsertFeedWithMeta
