# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iotics/api/host.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from iotics.api import common_pb2 as iotics_dot_api_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15iotics/api/host.proto\x12\niotics.api\x1a\x17iotics/api/common.proto\"A\n\x10GetHostIDRequest\x12-\n\x07headers\x18\x01 \x01(\x0b\x32\x13.iotics.api.HeadersR\x07headers\"\xa6\x01\n\x11GetHostIDResponse\x12-\n\x07headers\x18\x01 \x01(\x0b\x32\x13.iotics.api.HeadersR\x07headers\x12?\n\x07payload\x18\x02 \x01(\x0b\x32%.iotics.api.GetHostIDResponse.PayloadR\x07payload\x1a!\n\x07Payload\x12\x16\n\x06hostId\x18\x01 \x01(\tR\x06hostId2U\n\x07HostAPI\x12J\n\tGetHostID\x12\x1c.iotics.api.GetHostIDRequest\x1a\x1d.iotics.api.GetHostIDResponse\"\x00\x42}\n\x0e\x63om.iotics.apiB\tHostProtoP\x01Z>github.com/Iotic-Labs/iotic-go-proto-qapi/iotics/api;ioticsapi\xa2\x02\x03IAX\xaa\x02\nIotics.Api\xca\x02\nIotics\\Apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iotics.api.host_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.iotics.apiB\tHostProtoP\001Z>github.com/Iotic-Labs/iotic-go-proto-qapi/iotics/api;ioticsapi\242\002\003IAX\252\002\nIotics.Api\312\002\nIotics\\Api'
  _GETHOSTIDREQUEST._serialized_start=62
  _GETHOSTIDREQUEST._serialized_end=127
  _GETHOSTIDRESPONSE._serialized_start=130
  _GETHOSTIDRESPONSE._serialized_end=296
  _GETHOSTIDRESPONSE_PAYLOAD._serialized_start=263
  _GETHOSTIDRESPONSE_PAYLOAD._serialized_end=296
  _HOSTAPI._serialized_start=298
  _HOSTAPI._serialized_end=383
# @@protoc_insertion_point(module_scope)
