# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: iotics/api/input.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.timestamp_pb2
import iotics.api.common_pb2
import iotics.api.input_pb2


class InputAPIBase(abc.ABC):

    @abc.abstractmethod
    async def DeleteInput(self, stream: 'grpclib.server.Stream[iotics.api.input_pb2.DeleteInputRequest, iotics.api.input_pb2.DeleteInputResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DescribeInput(self, stream: 'grpclib.server.Stream[iotics.api.input_pb2.DescribeInputRequest, iotics.api.input_pb2.DescribeInputResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ReceiveInputMessages(self, stream: 'grpclib.server.Stream[iotics.api.input_pb2.ReceiveInputMessageRequest, iotics.api.input_pb2.ReceiveInputMessageResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CreateInput(self, stream: 'grpclib.server.Stream[iotics.api.input_pb2.CreateInputRequest, iotics.api.input_pb2.CreateInputResponse]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateInput(self, stream: 'grpclib.server.Stream[iotics.api.input_pb2.UpdateInputRequest, iotics.api.input_pb2.UpdateInputResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/iotics.api.InputAPI/DeleteInput': grpclib.const.Handler(
                self.DeleteInput,
                grpclib.const.Cardinality.UNARY_UNARY,
                iotics.api.input_pb2.DeleteInputRequest,
                iotics.api.input_pb2.DeleteInputResponse,
            ),
            '/iotics.api.InputAPI/DescribeInput': grpclib.const.Handler(
                self.DescribeInput,
                grpclib.const.Cardinality.UNARY_UNARY,
                iotics.api.input_pb2.DescribeInputRequest,
                iotics.api.input_pb2.DescribeInputResponse,
            ),
            '/iotics.api.InputAPI/ReceiveInputMessages': grpclib.const.Handler(
                self.ReceiveInputMessages,
                grpclib.const.Cardinality.UNARY_STREAM,
                iotics.api.input_pb2.ReceiveInputMessageRequest,
                iotics.api.input_pb2.ReceiveInputMessageResponse,
            ),
            '/iotics.api.InputAPI/CreateInput': grpclib.const.Handler(
                self.CreateInput,
                grpclib.const.Cardinality.UNARY_UNARY,
                iotics.api.input_pb2.CreateInputRequest,
                iotics.api.input_pb2.CreateInputResponse,
            ),
            '/iotics.api.InputAPI/UpdateInput': grpclib.const.Handler(
                self.UpdateInput,
                grpclib.const.Cardinality.UNARY_UNARY,
                iotics.api.input_pb2.UpdateInputRequest,
                iotics.api.input_pb2.UpdateInputResponse,
            ),
        }


class InputAPIStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.DeleteInput = grpclib.client.UnaryUnaryMethod(
            channel,
            '/iotics.api.InputAPI/DeleteInput',
            iotics.api.input_pb2.DeleteInputRequest,
            iotics.api.input_pb2.DeleteInputResponse,
        )
        self.DescribeInput = grpclib.client.UnaryUnaryMethod(
            channel,
            '/iotics.api.InputAPI/DescribeInput',
            iotics.api.input_pb2.DescribeInputRequest,
            iotics.api.input_pb2.DescribeInputResponse,
        )
        self.ReceiveInputMessages = grpclib.client.UnaryStreamMethod(
            channel,
            '/iotics.api.InputAPI/ReceiveInputMessages',
            iotics.api.input_pb2.ReceiveInputMessageRequest,
            iotics.api.input_pb2.ReceiveInputMessageResponse,
        )
        self.CreateInput = grpclib.client.UnaryUnaryMethod(
            channel,
            '/iotics.api.InputAPI/CreateInput',
            iotics.api.input_pb2.CreateInputRequest,
            iotics.api.input_pb2.CreateInputResponse,
        )
        self.UpdateInput = grpclib.client.UnaryUnaryMethod(
            channel,
            '/iotics.api.InputAPI/UpdateInput',
            iotics.api.input_pb2.UpdateInputRequest,
            iotics.api.input_pb2.UpdateInputResponse,
        )
