"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2019-2022 Iotic Labs Ltd. All rights reserved.

Iotics Web protocol definitions (interests)
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import iotics.api.common_pb2
import iotics.api.feed_pb2
import iotics.api.input_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class InputInterest(google.protobuf.message.Message):
    """An interest is the relationship between a Twin and an Input."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class DestinationInput(google.protobuf.message.Message):
        """InputInterest destination input identification."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INPUT_FIELD_NUMBER: builtins.int
        HOSTID_FIELD_NUMBER: builtins.int
        @property
        def input(self) -> iotics.api.input_pb2.Input:
            """Input to send the message to"""
        @property
        def hostId(self) -> iotics.api.common_pb2.HostID:
            """HostID to identify a remote input (Optional, keep empty if input is local)"""
        def __init__(
            self,
            *,
            input: iotics.api.input_pb2.Input | None = ...,
            hostId: iotics.api.common_pb2.HostID | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["hostId", b"hostId", "input", b"input"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["hostId", b"hostId", "input", b"input"]) -> None: ...

    SENDERTWINID_FIELD_NUMBER: builtins.int
    DESTINPUT_FIELD_NUMBER: builtins.int
    @property
    def senderTwinId(self) -> iotics.api.common_pb2.TwinID:
        """Sender twin unique identifier."""
    @property
    def destInput(self) -> global___InputInterest.DestinationInput:
        """a reference to the input of interest"""
    def __init__(
        self,
        *,
        senderTwinId: iotics.api.common_pb2.TwinID | None = ...,
        destInput: global___InputInterest.DestinationInput | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["destInput", b"destInput", "senderTwinId", b"senderTwinId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["destInput", b"destInput", "senderTwinId", b"senderTwinId"]) -> None: ...

global___InputInterest = InputInterest

class SendInputMessageRequest(google.protobuf.message.Message):
    """SendInputMessageRequest is used to send a message to a given input."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """SendInputMessageRequest payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MESSAGE_FIELD_NUMBER: builtins.int
        @property
        def message(self) -> iotics.api.input_pb2.InputMessage:
            """Message to send"""
        def __init__(
            self,
            *,
            message: iotics.api.input_pb2.InputMessage | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["message", b"message"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["message", b"message"]) -> None: ...

    class Arguments(google.protobuf.message.Message):
        """SendInputMessageRequest arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___InputInterest:
            """The interest"""
        def __init__(
            self,
            *,
            interest: global___InputInterest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """SendInputMessageRequest headers"""
    @property
    def args(self) -> global___SendInputMessageRequest.Arguments:
        """SendInputMessageRequest mandatory arguments"""
    @property
    def payload(self) -> global___SendInputMessageRequest.Payload:
        """SendInputMessageRequest payload"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___SendInputMessageRequest.Arguments | None = ...,
        payload: global___SendInputMessageRequest.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "payload", b"payload"]) -> None: ...

global___SendInputMessageRequest = SendInputMessageRequest

class SendInputMessageResponse(google.protobuf.message.Message):
    """SendInputMessageResponse is used to indicate a successful send."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADERS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """SendInputMessageResponse headers"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers", b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers", b"headers"]) -> None: ...

global___SendInputMessageResponse = SendInputMessageResponse

class Interest(google.protobuf.message.Message):
    """An interest is the relationship between a Twin and a Feed. For example, creating
    an interest on (following) a Feed results in any data shared on said Feed to be forwarded to
    the associated Twin. Interests can be revoked either by the subscriber or provider and there
    may only be one interest between any unique Twin and Feed combination.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class FollowedFeed(google.protobuf.message.Message):
        """FollowedFeed fully identify the (local or remote) feed to follow."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FEED_FIELD_NUMBER: builtins.int
        HOSTID_FIELD_NUMBER: builtins.int
        @property
        def feed(self) -> iotics.api.feed_pb2.Feed:
            """Followed feed identifier"""
        @property
        def hostId(self) -> iotics.api.common_pb2.HostID:
            """Feed remote host identifier (If not specified, the Interest is taken to be in scope of the host from which a request is made.)"""
        def __init__(
            self,
            *,
            feed: iotics.api.feed_pb2.Feed | None = ...,
            hostId: iotics.api.common_pb2.HostID | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feed", b"feed", "hostId", b"hostId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feed", b"feed", "hostId", b"hostId"]) -> None: ...

    FOLLOWERTWINID_FIELD_NUMBER: builtins.int
    FOLLOWEDFEED_FIELD_NUMBER: builtins.int
    @property
    def followerTwinId(self) -> iotics.api.common_pb2.TwinID:
        """Follower twin unique identifier."""
    @property
    def followedFeed(self) -> global___Interest.FollowedFeed:
        """a reference to the interested feed"""
    def __init__(
        self,
        *,
        followerTwinId: iotics.api.common_pb2.TwinID | None = ...,
        followedFeed: global___Interest.FollowedFeed | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["followedFeed", b"followedFeed", "followerTwinId", b"followerTwinId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["followedFeed", b"followedFeed", "followerTwinId", b"followerTwinId"]) -> None: ...

global___Interest = Interest

class CreateInterestRequest(google.protobuf.message.Message):
    """CreateInterestRequest is used to create an interest between a twin and a feed."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """CreateInterestRequest payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest: ...
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    class Arguments(google.protobuf.message.Message):
        """CreateInterestRequest mandatory arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TWINID_FIELD_NUMBER: builtins.int
        @property
        def twinId(self) -> iotics.api.common_pb2.TwinID:
            """Follower twin unique identifier"""
        def __init__(
            self,
            *,
            twinId: iotics.api.common_pb2.TwinID | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["twinId", b"twinId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["twinId", b"twinId"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """CreateInterestRequest headers"""
    @property
    def args(self) -> global___CreateInterestRequest.Arguments:
        """CreateInterestRequest arguments"""
    @property
    def payload(self) -> global___CreateInterestRequest.Payload:
        """CreateInterestRequest payload"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___CreateInterestRequest.Arguments | None = ...,
        payload: global___CreateInterestRequest.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "payload", b"payload"]) -> None: ...

global___CreateInterestRequest = CreateInterestRequest

class CreateInterestResponse(google.protobuf.message.Message):
    """CreateInterestResponse describes a successfully created interest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """CreateInterestResponse payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        ALREADYCREATED_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """Created interest"""
        alreadyCreated: builtins.bool
        """whether the interest exists already (creating an existing interest is idempotent)."""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
            alreadyCreated: builtins.bool = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["alreadyCreated", b"alreadyCreated", "interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """CreateInterestResponse headers"""
    @property
    def payload(self) -> global___CreateInterestResponse.Payload:
        """CreateInterestResponse payload"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        payload: global___CreateInterestResponse.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> None: ...

global___CreateInterestResponse = CreateInterestResponse

class ListAllInterestsRequest(google.protobuf.message.Message):
    """---------------------------------------

    ListAllInterestsRequest is used to list all interests initiated by a given twin.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Arguments(google.protobuf.message.Message):
        """ListAllInterestsRequest mandatory arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TWINID_FIELD_NUMBER: builtins.int
        @property
        def twinId(self) -> iotics.api.common_pb2.TwinID:
            """Follower twin unique identifier"""
        def __init__(
            self,
            *,
            twinId: iotics.api.common_pb2.TwinID | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["twinId", b"twinId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["twinId", b"twinId"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    RANGE_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ListAllInterestsRequest headers"""
    @property
    def args(self) -> global___ListAllInterestsRequest.Arguments:
        """ListAllInterestsRequest arguments"""
    @property
    def range(self) -> iotics.api.common_pb2.Range:
        """Limit the results according to the value (optional: when not supplied, assume no default limits required - platform specific)"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___ListAllInterestsRequest.Arguments | None = ...,
        range: iotics.api.common_pb2.Range | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "range", b"range"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers", "range", b"range"]) -> None: ...

global___ListAllInterestsRequest = ListAllInterestsRequest

class ListAllInterestsResponse(google.protobuf.message.Message):
    """ListAllInterestsResponse describes all the interest initiated by the given twin."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """ListAllInterestsResponse payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTERESTS_FIELD_NUMBER: builtins.int
        @property
        def interests(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Interest]: ...
        def __init__(
            self,
            *,
            interests: collections.abc.Iterable[global___Interest] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["interests", b"interests"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """ListAllInterestsResponse headers"""
    @property
    def payload(self) -> global___ListAllInterestsResponse.Payload:
        """ListAllInterestsResponse payload."""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        payload: global___ListAllInterestsResponse.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> None: ...

global___ListAllInterestsResponse = ListAllInterestsResponse

class FetchInterestRequest(google.protobuf.message.Message):
    """---------------------------------------

    FetchInterestRequest is used to initiate a stream to get the feed data shared on a given interest.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Arguments(google.protobuf.message.Message):
        """FetchInterestRequest mandatory arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """The interest"""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    FETCHLASTSTORED_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """FetchInterestRequest headers"""
    @property
    def args(self) -> global___FetchInterestRequest.Arguments:
        """FetchInterestRequest arguments"""
    @property
    def fetchLastStored(self) -> google.protobuf.wrappers_pb2.BoolValue:
        """whether to fetch the last stored value if available (false by default)"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___FetchInterestRequest.Arguments | None = ...,
        fetchLastStored: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "fetchLastStored", b"fetchLastStored", "headers", b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "fetchLastStored", b"fetchLastStored", "headers", b"headers"]) -> None: ...

global___FetchInterestRequest = FetchInterestRequest

class FetchInterestResponse(google.protobuf.message.Message):
    """FetchInterestResponse describes a feed value shared on a given interest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """FetchInterestResponse payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        FEEDDATA_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """The interest"""
        @property
        def feedData(self) -> iotics.api.common_pb2.FeedData:
            """The shared data"""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
            feedData: iotics.api.common_pb2.FeedData | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["feedData", b"feedData", "interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["feedData", b"feedData", "interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """FetchInterestResponse headers"""
    @property
    def payload(self) -> global___FetchInterestResponse.Payload:
        """FetchInterestResponse payload"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        payload: global___FetchInterestResponse.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> None: ...

global___FetchInterestResponse = FetchInterestResponse

class FetchLastStoredRequest(google.protobuf.message.Message):
    """---------------------------------------

    FetchLastStoredRequest is used to fetch the last stored value on a given interest if available.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Arguments(google.protobuf.message.Message):
        """FetchLastStoredRequest mandatory arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """The interest"""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """FetchLastStoredRequest headers"""
    @property
    def args(self) -> global___FetchLastStoredRequest.Arguments:
        """FetchLastStoredRequest arguments"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___FetchLastStoredRequest.Arguments | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers"]) -> None: ...

global___FetchLastStoredRequest = FetchLastStoredRequest

class DeleteInterestRequest(google.protobuf.message.Message):
    """---------------------------------------

    DeleteInterestRequest is used to delete an interest.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Arguments(google.protobuf.message.Message):
        """DeleteInterestRequest mandatory arguments."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """The interest"""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    ARGS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DeleteInterestRequest headers"""
    @property
    def args(self) -> global___DeleteInterestRequest.Arguments:
        """DeleteInterestRequest args"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        args: global___DeleteInterestRequest.Arguments | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["args", b"args", "headers", b"headers"]) -> None: ...

global___DeleteInterestRequest = DeleteInterestRequest

class DeleteInterestResponse(google.protobuf.message.Message):
    """DeleteInterestResponse describes a deleted interest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class Payload(google.protobuf.message.Message):
        """DeleteInterestResponse payload."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        INTEREST_FIELD_NUMBER: builtins.int
        @property
        def interest(self) -> global___Interest:
            """The deleted interest."""
        def __init__(
            self,
            *,
            interest: global___Interest | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["interest", b"interest"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """DeleteInterestResponse headers"""
    @property
    def payload(self) -> global___DeleteInterestResponse.Payload:
        """DeleteInterestResponse payload"""
    def __init__(
        self,
        *,
        headers: iotics.api.common_pb2.Headers | None = ...,
        payload: global___DeleteInterestResponse.Payload | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers", b"headers", "payload", b"payload"]) -> None: ...

global___DeleteInterestResponse = DeleteInterestResponse
