"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.rpc.status_pb2
import iotics.api.common_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SparqlResultType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _SparqlResultTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SparqlResultType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SPARQL_JSON: _SparqlResultType.ValueType  # 0
    """Applicable to SELECT/ASK (SPARQL 1.1 Query Results JSON Format)"""

    SPARQL_XML: _SparqlResultType.ValueType  # 1
    """Applicable to SELECT/ASK (SPARQL 1.1 Query Results XML Format)"""

    SPARQL_CSV: _SparqlResultType.ValueType  # 2
    """Applicable to SELECT/ASK (SPARQL 1.1. Query Results CSV Format)"""

    RDF_TURTLE: _SparqlResultType.ValueType  # 3
    """Applicable to CONSTRUCT/DESCRIBE (Terse RDF Triple Language)"""

    RDF_XML: _SparqlResultType.ValueType  # 4
    """Applicable to CONSTRUCT/DESCRIBE (RDF 1.1 XML)"""

    RDF_NTRIPLES: _SparqlResultType.ValueType  # 5
    """Applicable to CONSTRUCT/DESCRIBE (RDF 1.1 N-Triples)"""

class SparqlResultType(_SparqlResultType, metaclass=_SparqlResultTypeEnumTypeWrapper):
    """SparqlResultType defines the result content types for SPARQL requests. Note that applicable content types depend on
    the type of query.
    """
    pass

SPARQL_JSON: SparqlResultType.ValueType  # 0
"""Applicable to SELECT/ASK (SPARQL 1.1 Query Results JSON Format)"""

SPARQL_XML: SparqlResultType.ValueType  # 1
"""Applicable to SELECT/ASK (SPARQL 1.1 Query Results XML Format)"""

SPARQL_CSV: SparqlResultType.ValueType  # 2
"""Applicable to SELECT/ASK (SPARQL 1.1. Query Results CSV Format)"""

RDF_TURTLE: SparqlResultType.ValueType  # 3
"""Applicable to CONSTRUCT/DESCRIBE (Terse RDF Triple Language)"""

RDF_XML: SparqlResultType.ValueType  # 4
"""Applicable to CONSTRUCT/DESCRIBE (RDF 1.1 XML)"""

RDF_NTRIPLES: SparqlResultType.ValueType  # 5
"""Applicable to CONSTRUCT/DESCRIBE (RDF 1.1 N-Triples)"""

global___SparqlResultType = SparqlResultType


class SparqlQueryRequest(google.protobuf.message.Message):
    """SparqlQueryRequest describes a SPARQL query."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """SPARQL query request payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        RESULTCONTENTTYPE_FIELD_NUMBER: builtins.int
        QUERY_FIELD_NUMBER: builtins.int
        resultContentType: global___SparqlResultType.ValueType
        """The desired result content type. Note that choosing an invalid result type for the type of query will result in
        an error status reported in the response. (See SparqlResultType for valid content-query type combinations.)
        """

        query: builtins.bytes
        """A UTF8-encoded SPARQL 1.1 query"""

        def __init__(self,
            *,
            resultContentType: global___SparqlResultType.ValueType = ...,
            query: builtins.bytes = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["query",b"query","resultContentType",b"resultContentType"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    SCOPE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """SPARQL query request headers"""
        pass
    scope: iotics.api.common_pb2.Scope.ValueType
    """SPARQL query request scope"""

    @property
    def payload(self) -> global___SparqlQueryRequest.Payload:
        """SPARQL query request payload"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        scope: iotics.api.common_pb2.Scope.ValueType = ...,
        payload: typing.Optional[global___SparqlQueryRequest.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload","scope",b"scope"]) -> None: ...
global___SparqlQueryRequest = SparqlQueryRequest

class SparqlQueryResponse(google.protobuf.message.Message):
    """SparqlQueryResponse is a part of a result for a SPARQL query request. Multiple chunks form a complete result. Related
    chunks can be identified by a combination of:
    - The host ID (unset for local results)
    - Client reference (in headers, set by caller)
    - Chunk sequence number
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """Payload of the query result chunk"""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        REMOTEHOSTID_FIELD_NUMBER: builtins.int
        SEQNUM_FIELD_NUMBER: builtins.int
        LAST_FIELD_NUMBER: builtins.int
        STATUS_FIELD_NUMBER: builtins.int
        CONTENTTYPE_FIELD_NUMBER: builtins.int
        RESULTCHUNK_FIELD_NUMBER: builtins.int
        @property
        def remoteHostId(self) -> iotics.api.common_pb2.HostID:
            """Result host identifier. Indicates from which host this result chunk came from. For a local result, this field
            will be unset.
            """
            pass
        seqNum: builtins.int
        """Position of a chunk in result from a given host (and request). The first chunk has a sequence number of 0."""

        last: builtins.bool
        """Indicates whether this is the last chunk from a given host, for a specific request. Results for different
        requests can be identified by setting a unique clientRef in the request headers.
        """

        @property
        def status(self) -> google.rpc.status_pb2.Status:
            """Result error status (only applicable to local results, i.e. when remoteHostId is unset). If set, this will
            indicate a problem with running the query (e.g. invalid syntax or content type) as opposed to a more general
            issue (in which case the standard gRPC error mechanism will be used and the stream terminated).
            """
            pass
        contentType: global___SparqlResultType.ValueType
        """Content type of the result."""

        resultChunk: builtins.bytes
        """Query result chunk, encoded according to actualType.
        Note that:
        - The maximum size of each chunk is host-specific.
        """

        def __init__(self,
            *,
            remoteHostId: typing.Optional[iotics.api.common_pb2.HostID] = ...,
            seqNum: builtins.int = ...,
            last: builtins.bool = ...,
            status: typing.Optional[google.rpc.status_pb2.Status] = ...,
            contentType: global___SparqlResultType.ValueType = ...,
            resultChunk: builtins.bytes = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["remoteHostId",b"remoteHostId","status",b"status"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["contentType",b"contentType","last",b"last","remoteHostId",b"remoteHostId","resultChunk",b"resultChunk","seqNum",b"seqNum","status",b"status"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """Headers for the query result. clientRef within can be used to identify which query the result applies to."""
        pass
    @property
    def payload(self) -> global___SparqlQueryResponse.Payload:
        """SPARQL query result chunk payload."""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___SparqlQueryResponse.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___SparqlQueryResponse = SparqlQueryResponse

class SparqlUpdateRequest(google.protobuf.message.Message):
    """Performs a SPARQL update against custom metadata only."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Payload(google.protobuf.message.Message):
        """SPARQL update request payload."""
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        UPDATE_FIELD_NUMBER: builtins.int
        update: builtins.bytes
        """A UTF8-encoded SPARQL 1.1 update"""

        def __init__(self,
            *,
            update: builtins.bytes = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["update",b"update"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """SPARQL update request headers"""
        pass
    @property
    def payload(self) -> global___SparqlUpdateRequest.Payload:
        """SPARQL update request payload."""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        payload: typing.Optional[global___SparqlUpdateRequest.Payload] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers","payload",b"payload"]) -> None: ...
global___SparqlUpdateRequest = SparqlUpdateRequest

class SparqlUpdateResponse(google.protobuf.message.Message):
    """Response of the SPARQL update request."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADERS_FIELD_NUMBER: builtins.int
    @property
    def headers(self) -> iotics.api.common_pb2.Headers:
        """SPARQL update response headers"""
        pass
    def __init__(self,
        *,
        headers: typing.Optional[iotics.api.common_pb2.Headers] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["headers",b"headers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["headers",b"headers"]) -> None: ...
global___SparqlUpdateResponse = SparqlUpdateResponse
